name: Security Pipeline

on: [push, pull_request]

jobs:
  sonarcloud:
    name: Analyse Statique (SAST) avec SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installer Java (nécessaire pour SonarScanner)
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Analyser avec SonarCloud
        run: |
          curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli.zip -d $HOME/
          export PATH="$HOME/sonar-scanner-4.7.0.2747-linux/bin:$PATH"
          sonar-scanner \
            -Dsonar.organization=sskiizenss \
            -Dsonar.projectKey=dvna \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONARCLOUD_TOKEN }}
